name: CI/CD
on:
  workflow_dispatch:
  push:
    branches: [ release ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Boostart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: | 
          cd ~/boostart
          git pull
          cd ./client
          npm ci
          npm run build:prod
          cd ../server
          npm ci
          nohup npm run start
